name: MSBuild

on:
  workflow_call:
    inputs:
      runner:
        description: Runner
        default: windows-latest
        required: false
        type: string
      repository:
        description: Repository
        required: true
        type: string
      dotnet_version:
        description: Dotnet Version
        default: 8.0.x
        required: false
        type: string
      solution_path:
        description: Solution Path
        required: true
        type: string
      build_configuration:
        description: Build Configuration
        default: Release
        required: false
        type: string
      runtime_identifier:
        description: Runtime Identifier
        required: false
        type: string

jobs:
  build:
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: ${{ inputs.repository }}
      - name: Setup dotnet
        uses: actions/setup-dotnet@6bd8b7f7774af54e05809fcc5431931b3eb1ddee #v4.0.1
        with:
          dotnet-version: ${{ inputs.dotnet_version }}
      - name: Disable problem matcher
        run: Write-Output "::remove-matcher owner=csc::"
      - name: Setup msbuild
        uses: microsoft/setup-msbuild@6fb02220983dee41ce7ae257b6f4d8f9bf5ed4ce # v2
      - name: Restore dependencies
        run: |
          dotnet restore ${{ github.workspace }}\${{ inputs.solution_path }} /p:Configuration=${{ inputs.build_configuration }} --runtime=${{ inputs.runtime_identifier }}
      - name: Build Solution
        run: |
          msbuild ${{ github.workspace }}\${{ inputs.solution_path }} /p:Configuration=${{ inputs.build_configuration }}
