name: NPM Build

on:
  workflow_call:
    inputs:
      runner:
        description: Runner
        default: ubuntu-latest
        required: false
        type: string
      repository:
        description: Repository
        required: true
        type: string
      node_version:
        description: Node Version
        default: 20
        required: false
        type: number

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5
        with:
          repository: ${{ inputs.repository }}
      - name: Setup node
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4.0.2
        with:
          node-version: ${{ inputs.node_version }}
          cache: npm
      - name: Install dependencies
        run: npm ci --force
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm run test --if-present
