name: NPM Build

on:
  workflow_call:
    inputs:
      runner:
        description: Runner
        default: ubuntu-latest
        required: false
        type: string
      repository:
        description: Repository
        required: true
        type: string
      node_version:
        description: Node Version
        default: 20
        required: false
        type: number

jobs:
  build:
    name: Build
    runs-on: ${{ inputs.runner }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          repository: ${{ inputs.repository }}
      - name: Setup node
        uses: actions/setup-node@0a44ba7841725637a19e28fa30b79a866c81b0a6 # v4.0.4
        with:
          node-version: ${{ inputs.node_version }}
          cache: npm
      - name: Install dependencies
        run: npm ci --force
      - name: Build
        run: npm run build --if-present
      - name: Test
        run: npm run test --if-present
